name: master
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      config: 'Release'
      framework: 'net7.0'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100
        include-prerelease: true
    - name: Workload Install
      run: dotnet workload install macos
    - name: Restore Dependencies
      run: dotnet restore ./src/Phototis/Phototis.Wasm/Phototis.Wasm.csproj
    - name: Build 
      run: dotnet build ./src/Phototis/Phototis.Wasm/Phototis.Wasm.csproj --no-restore -f $framework -c $config
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3            
      with:
        name: pages
        path: ./src/Phototis/Phototis.Wasm/bin/${{env.config}}/${{env.framework}}/dist/
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    name: Deploy    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: pages
        path: ./src/Phototis/Phototis.Wasm/bin/${{env.config}}/${{env.framework}}/dist/
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./src/Phototis/Phototis.Wasm/bin/${{env.config}}/${{env.framework}}/dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
